### PR TITLE
upgrade of print-error and universal-webpack

### PR DESCRIPTION
**Pull request by alexicum**
1. upgrade of print-error and universal-webpack
2. Notification about rebuilding of rendering server

### CODE REVIEW

**Comment by catamphetamine** [comment]
`print-error` is never used directly in this project so it shouldn't be in dependencies.

Webpack already outputs `webpack building...` each time it starts an incremental build.

**Comment by alexicum** [comment]
Yes:
```
webpack building...
[nodemon] files triggering change check: client\build\server\server.js
Hash: [nodemon] matched rule: **\e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\client\build\server/**/*
a0a7c9ef9b1b93a90e46[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] client\build\server\server.js


Version: webpack [nodemon] files triggering change check: client\build\server\server.js.map
[nodemon] matched rule: **\e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\client\build\server/**/*
[nodemon] changes after filters (before/after): 1/0
2.2.1
Time: 531ms
        Asset     Size  Chunks             Chunk Names
    server.js  82.3 kB       0  [emitted]  server
server.js.map  45.4 kB       0  [emitted]  server
   [5] ./src/redux/users.js 5.34 kB {0} [built]
    + 34 hidden modules
[nodemon] starting `node ./client/rendering-service/entry.js`
[nodemon] child pid: 24348
webpack built b6622f44d7601ddf57be in 2543ms
Webpage rendering service is listening at port 3002
```
But it's about 15 seconds after `webpack built b6622f44d7601ddf57be in 2543ms`
and before `Webpage rendering service is listening at port 3002` appears.

**Comment by catamphetamine** [comment]
Then it's a serious performance bottleneck in your configuration because I don't experience a 15 sec delay.
My delay is about 3-4 seconds, and the more React components are there the longer it gets.
Having a 15 sec delay is unacceptable for development, therefore the issue is not in the absence of the message but rather in the abnormally long delay.

**Comment by alexicum** [comment]
built universal-webpack with some performance calc.
Getting 26-30sec delays:

> webpack built 9148e8386c01fdab43f6 in 1728ms
> Webpage rendering service is building...
> BEFORE const starter = require(server_bundle_path)
> AFTER const starter = require(server_bundle_path). **26890 ms**.
> Webpage rendering service is listening at port 3002

**Comment by catamphetamine** [comment]
Yes, it loads too much javascript code in your project I guess.
Maybe some code parts are very slow in your project.

**Comment by alexicum** [comment]
I didn't change anything in sample.

**Comment by catamphetamine** [comment]
Ok, so you're saying it's the sample project.
On my machine (OS X) it seems ok.
Maybe it's your machine somehow.
Maybe babel again.
Actually, there was a Babel issue once:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/issues/5
I guess on your machine (Windows) babel has a bug and doesn't ignore the server-side bundle therefore the long parsing time.
That's for you to investigate.

**Comment by catamphetamine** [comment]
Maybe on windows the ignore function doesn't work.
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/babel-register.js
Check that and rewrite if neccessary.

**Pull request closed without merging**
